# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e10103a794091b557f8ff3d43ca8f2dccd1aa1b4b8830fc5b6b39a3dba26fe7273ec3ab30e762ab54ba1e124559dba8d1d9e3a70ea1637211500762a397706b

test:
  secret_key_base: 419b8ce10d830542572f57b8b49abfc8a0d4c97f54a6c823d8edd8c78f76f95cf1a12edfc2ff8a5b1737c99bb71c05e978bad0b3d6402bcfdceb53da7cfccb9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
